### ISSUE TITLE
Work with each club that has a meeting to do setup for it

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#146]
- Do any setup for the club from our end (like having a project field in the feedback form)
- Make sure that they know which workshop to run
- This is not to help them improve the club experience

**Comment by hellyeah** [comment]
Clubs that have meetings this week are in #148

**Comment by jonleung** [comment]
I corresponded with almost every Labs leader that had a meeting this week (Bogdan, Jiahao, Teagan, and Tejas). I missed Gemma because I didn't realize she had a meeting this week.

For each leader, I made sure they knew about the following:

- the fancy feedback form that Max made
- the portfolio workshop and Twilio workshop
- how to run the above workshops

I also answered any questions they had.
