### ISSUE TITLE
Every club that had meetings last week should submit a case study

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#147]
Can you start by finding out which clubs had meetings last week and comment with a checklist of them, just so we can keep track in this issue?

Example checklist:

- [ ] Beeblebrox High School
- [ ] Manjaro High School

When a case study is submitted, can you check off the high school in the checklist it's for and referece the pull request that the case study is submitted in.

Example:

- [x] Beeblebrox High School (hackedu/hackedu#4242)
- [ ] Manjaro High School

**Comment by jonleung** [comment]
I've decided to track these inside of https://clubs.hackedu.us instead so everything is more consolidated. You can find the information in the "Schools" sheet in the "Week of Sept 14th Checkin"

**Comment by MaxWofford** [comment]
@jonleung If this is being tracked somewhere else should this issue stay open?

**Comment by jonleung** [comment]
@MaxWofford, even though the data for this task is tracked elsewhere, I want to keep the issue open because I want to track the status of the task (which is not yet finished yet).

Here is the current status:

Just as a status update:

| Club Leader Name   | Submitted Status                                                                         |
|:-------------------|:-----------------------------------------------------------------------------------------|
| Gemma Busoni       | recap merged                                                                             |
| Bogdan Vitoc       | he'll be writing one as soon as he can                                                   |
| Jiahao Kuang       | submitted pull request, waiting for him to fix some errors                               |
| Teagan Mullholland | submitted planning document which is being reviewed, has not submitted a post mortem yet |
| Tejas Manohar      | merged planning, waiting on recap                                                        |

**Comment by zachlatta** [comment]
Can you add links to the pull requests submitted to that table?

On Sat, Sep 19, 2015 at 7:18 PM, Jonathan Leung <notifications@github.com>
wrote:

> @MaxWofford <https://github.com/MaxWofford>, even though the data for
> this task is tracked elsewhere, I want to keep the issue open because I
> want to track the status of the task (which is not yet finished yet).
>
> Here is the current status:
>
> Just as a status update:
> Club Leader Name Submitted Status Gemma Busoni recap merged Bogdan Vitoc he'll
> be writing one as soon as he can Jiahao Kuang submitted pull request,
> waiting for him to fix some errors Teagan Mullholland submitted planning
> document which is being reviewed, has not submitted a post mortem yet Tejas
> Manohar merged planning, waiting on recap
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/147#issuecomment-141729258>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
@zachlatta, yeah I'll do that in a bit.

**Comment by jonleung** [comment]
@zachlatta I updated the table with links to the pull requests.

**Comment by jonleung** [comment]
@zachlatta I'll let you handle closing this issue.
