### ISSUE TITLE
Record workshops being run by each Labs club in the week of October 5th in https://clubs.hackedu.us

### ISSUE THREAD

**Issue by jonleung** [hackedu/meta#192]
If there isn't already an entry for their meeting, create one in the Meetings sheet in https://clubs.hackedu.us and record which workshop they're running in the curriculum plans column.

**Comment by jonleung** [comment]
Decided not to do this because it is no longer valuable considering the fact that we have this week's data.

**Comment by zachlatta** [comment]
I think it's valuable to have historical data as well. I want to see what
the progression of curriculum plans for clubs is.

Going to reopen because it was committed to at the beginning of the week.

On Thu, Oct 15, 2015 at 8:44 PM, Jonathan Leung <notifications@github.com>
wrote:

> Decided not to do this because it is no longer valuable considering the
> fact that we have this week's data.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/meta/issues/192#issuecomment-148591900>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
@zachlatta agreed. 

Done.
