### ISSUE TITLE
@hellyeah's clubs for the week

### ISSUE THREAD

**Issue by zachlatta** [hackedu/meta#247]
See #244 for full details.

Check off each club once the requirements in #244 are met. These are
@hellyeah's clubs:

- [x] Elizabeth High School
- [x] Project Cipher
- [ ] Columbia Secondary School
- [ ] College Park High School

**Comment by hellyeah** [comment]
Raw notes from call w/ Jevin

Hosted first formal workshop meeting yesterday

Did a custom-version of jon’s portfolio workshops
—added a bit more stuff to it for more depth
—sound, background image, space for projects
http://nguyenbrian.github.io/john-cenas-personal-website/
http://qureshiomar.github.io/snoopdoggs-website/

Did it in pairs
—worked really well with this one
—bounced questions off
—at the beginning they weren’t asking questions
—we had to facilitate
—do you know where your partners at
—what are you doing right now?
—are you added anything extra

Super effective: walk around and ask them every once in a while: tell us what your partner’s doing right now.

Getting over the hump of what your partner’s doing

Steps we went through were on C9
—modified his using C9 instead of JSBin

https://docs.google.com/document/d/1jCkOlEbgu_mCJDYCEdBk-rUSqTicHQy8YutEJ5MM6mY/edit?usp=sharing

One of the quotations i put was the wrong way
—when they asked their partner what they were doing, almost everyone realized they were stuck on the same problem (our error) and that jumpstarted conversation and connection

We had a bit more time 
—had 2 hours and a bit
—finished 1 hr and 50 minutes
—everyone finished at different intervals bc they had different experience

When you finished, people didn’t just close their laptop and leave
—they kept wanting to add more to their websites
—we gave them a lot of freedom 

Optimal meeting: when you say meeting is over, you can’t even kick people out the door

Pre-meeting
We made the whole workshop
—jowl pointed out things he thought could be better
—i went through it and made my own website
—tested it with his older brother (who’s inexperienced)
—they made it more thorough and in-depth

we let people know the meeting was going to happen on sunday the wednesday before
—helped coordinate the carpools
—we have a slack #rides

got some feedback: 4 responses
—filled it out in the form — got like 5 responses — waiting on 10ish more
—pair
—start faster — we chilled at the beginning
—easy to follow workshop — explained every step out — gifs and everything
—environment was really friendly

Everyone had finished the workshop at the end
—some people had to go right after bc they wanted to continue to add things instead of filling out feedback
—messaged them personally on slack an hour ago
—following up with them

People trickled in
—we had a pool table there
—had music on in the background
—we didn’t want people to start and then have people come in
—we are a bit more organized: know who’s coming
—had a party day before where people got to know each others names
—if people can’t make it, they msg us on slack

Names is the most important thing
—when you ask someone’s name when they walk in
—being able to call people by their names emphasizes that you actually care
—hits a lot of people by surprise when you call someone by their name bc people just expect you to forget their name
—brings level of uncomfortability way way way down
—ask people’s name right away
—15 people is easy if you just try

Music led into the mood a lot
—even while people are coding 
—we have a spotify playlist that anyone can add music to

We were going through the workshop at the same time they were
—my computer was hooked up to the projector
—when I would get ahead, I’d leave my site up and walk around

Don’t hover over people; phrasing of questions is important
—because I was doing it too, I could ask: “i used this color. what background color did you use for your thing” instead of “what are you doing right now”
—creates more of a conversation 
—asking from the perspective of you doing it too

As you’re going through the workshop, keep it personal too. Don’t just ask about workshop. it’s ok to have some conversation while they are doing their workshop, especially if you ask personal things, maybe things they’ve mentioned before.

What’s the biggest thing you’ll do differently?
—starting a bit quicker in the beginning
—make sure we have everything setup
—intro of the workshop could be done better
——went through it too quickly: should’ve talked more in-depth about workshop
——transitioning them into the workshop by doing the first step with them: importance of googling

People are afraid to be harsh/mean

When we give out feedback, maybe mention that we want you to be mean. Intent of feedback is for us to get better. We’re not going to get mad at you; we’re going to be happy bc we want to improve, want to get better.

Attendance: 13/18
—want 18
—20 would be cap

City itself has picked up on what we’re doing
—want to host workshops at libraries
—with more people
—people who came to first meeting are going to help run those workshops

**Comment by hellyeah** [comment]
Amy had her meeting -- it went well.

Going to ask if she can hop on a call tomorrow after school to recap it with me. 

Still waiting on a response from Abby. Might try email tomorrow.

**Comment by hellyeah** [comment]
Did not complete this issue.

Abby responded. I will jump on a call with her this week.

Texted Vene and emailed Vene/Ilisha. No response.

**Comment by hellyeah** [comment]
Amy: https://github.com/hackedu/hackedu/pull/446
Jevin: https://github.com/hackedu/hackedu/pull/445
