### ISSUE TITLE
Create private repo and subtree for labs

### ISSUE THREAD

**Issue by jonleung** [hackedu/meta#99]

**Comment by zachlatta** [comment]
I've created `hackedu/labs`, but I'll need to figure out how to best include it in the public labs repo.

**Comment by zachlatta** [comment]
Alright, so after a bit more research I'm having trouble finding a nice way to incorporate a private subdirectory into this public repo. Most people seem to do the opposite and create public submodules or subtrees inside of private repositories.

Instead of trying to create a submodule or subtree in this public repo that's private, I decided to rename `hackedu/labs` to `hackedu/labs-private` and I submitted hackedu/labs-private#4 to better describe the purpose of the repo.
